# Generated by Django 3.1.5 on 2021-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False)),
                ('col_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'collect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_ctime', models.DateTimeField()),
                ('c_playtime', models.IntegerField()),
                ('c_content', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_viewingtime', models.DateTimeField()),
                ('h_duration', models.IntegerField()),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=50)),
                ('m_actors', models.CharField(blank=True, max_length=50, null=True)),
                ('m_directors', models.CharField(blank=True, max_length=50, null=True)),
                ('m_nation', models.CharField(blank=True, max_length=50, null=True)),
                ('m_releasedate', models.DateField(blank=True, db_column='m_releaseDate', null=True)),
                ('m_duration', models.IntegerField(blank=True, null=True)),
                ('m_introduce', models.CharField(blank=True, max_length=255, null=True)),
                ('m_scenario', models.CharField(blank=True, max_length=255, null=True)),
                ('m_poster', models.CharField(blank=True, max_length=50, null=True)),
                ('m_score', models.FloatField(blank=True, null=True)),
                ('m_link', models.CharField(blank=True, max_length=255, null=True)),
                ('m_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_username', models.CharField(max_length=20, unique=True)),
                ('u_password', models.CharField(max_length=20)),
                ('u_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('u_email', models.CharField(blank=True, max_length=20, null=True)),
                ('u_gender', models.CharField(blank=True, max_length=2, null=True)),
                ('u_age', models.IntegerField(blank=True, null=True)),
                ('u_nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('u_head_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
